#!/bin/sh -ex

DEVICE=${1:-"/dev/sda"}

[ -b $DEVICE ] || { echo "$DEVICE could not be found. Aborting."; exit 1; }

set_fstab_device() {
	uci set fstab.usb_overlay.device="${DEVICE}1"
	uci commit fstab
}

set_uuid() {
	uuid=$(blkid ${DEVICE}1 | tr ' ' \\n | grep ^UUID | cut -d\" -f2)

	[ -z "$uuid" ] && echo "Cannot get UUID" || {
		echo "UUID of ${DEVICE}1 is $uuid"
		uci set fstab.usb_overlay.uuid="$uuid"
		uci commit fstab
	}
}

set_enabled() {
	uci set fstab.usb_overlay.enabled=1
	uci commit fstab
}

grep ^$DEVICE /proc/mounts && {
	echo "$DEVICE mounted, exiting..."
	set_uuid
	exit 1
}

dd if=/dev/zero of=$DEVICE bs=512 count=2

sync
sleep 1

sfdisk -L -q $DEVICE << EOF
,,L
EOF

sync
sleep 1

mkfs.ext4 -L wibed-overlay ${DEVICE}1 || { echo "Partitioning $DEVICE failed."; exit 3; }

sync
sleep 1

set_fstab_device
set_uuid
set_enabled

sleep 5 && block mount

exit 0
