#!/usr/bin/lua

local crc = require "crc16"
local fs  = require "nixio.fs"
local uci = require "uci"
local iw  = require "iwinfo"
local ucic = "wibed"
local x = uci:cursor()

local function node_id()
	local dev = assert(x:get("wbm", "network", "primary_dev"))
	local mac = assert(fs.readfile("/sys/class/net/"..dev.."/address"))
	local hash = crc.hash(mac)
	return math.floor(hash / 256), hash % 256
end

local function generate_address()
	local r1, r2 = node_id()
	local ipv4_template = assert(x:get(ucic, "management", "ipv4_net"))
	local ipv6_template = assert(x:get(ucic, "management", "ipv6_net"))

	local function hex(x) return string.format("%02x", x) end

	return ipv4_template:gsub("R1", r1):gsub("R2", r2),
	       ipv6_template:gsub("R1", hex(r1)):gsub("R2", hex(r2)) 
-- XXX: id should be hex coded but for backwards compat keep it decimal
end

local function generate_ssid()
	local id = assert(x:get(ucic, "management", "ssid"))
	local r1, r2 = node_id()
	return string.format("%s-%02x%02x", id, r1, r2)
end

local function set_hostname()
	local r1, r2 = node_id()
	local hostname = string.format("wibed-%02x%02x", r1, r2)

	x:foreach("system", "system", function(s)
		x:set("system", s[".name"], "hostname", hostname)
	end)
	x:save("system")
	x:commit("system")

	fs.writefile("/proc/sys/kernel/hostname", hostname)
end

local function printf(fmt, ...)
	print(string.format(fmt, ...))
end

local function printr(r)
	local i,v
	for i,v in ipairs(r) do
		printf("%d -> %s",i,v)
	end
end

local function is_net(dev)
	local r = os.execute(string.format("ls /sys/class/net/%s >/dev/null 2>&1",dev))
	return r==0
end

local function is_wifi(dev)
	local r = os.execute(string.format("ls /sys/class/net/%s/phy80211/ >/dev/null 2>&1",dev))
	return r==0
end

local function reset_wifi()
	print("Reconfiguring wifi devices...")
	os.execute('echo "" > /etc/config/wireless')
	os.execute('wifi detect > /etc/config/wireless')
end

local function wifi_up()
	os.execute("wifi")
end

local function split_ifaces(ifaces)
	local _,i
	local et = {}
	local wi = {}
	for _,i in ipairs(ifaces) do
		if x:get("wireless",i) == "wifi-device" then
			table.insert(wi,i)
		else if is_net(i) then
			table.insert(et,i)
		 	end
		end
	end
	return et,wi
end

local function set_batadv(dev)
	local ifn = "bat_"..dev
	x:set("batman-adv","bat0","mesh")
	x:set("batman-adv","bat0","bridge_loop_avoidance","1")
	x:set("network",ifn,"interface")
	x:set("network",ifn,"ifname",dev)
	x:set("network",ifn,"proto","batadv")
	x:set("network",ifn,"mesh","bat0")
	if is_wifi(dev) then
		x:set("network",ifn,"mtu","1528")
	end
end

local function set_mgmt_net()
	print("Configuring management network devices")
	local ifaces,_ = split_ifaces(x:get(ucic, "management", "ifaces"))
	table.insert(ifaces,"bat0")
	local ipv4, ipv6 = generate_address()

	x:set("network", "mgmt", "interface")
	x:set("network", "mgmt", "type","bridge")
	x:set("network", "mgmt", "proto", "static")
	x:set("network", "mgmt", "ipaddr", ipv4)
	x:set("network", "mgmt", "netmask", "255.255.0.0")
	x:set("network", "mgmt", "ip6addr", ipv6)
	x:set("network", "mgmt", "ifname", ifaces)
	
	x:set("network", "mgmt_dyn", "interface")
	x:set("network", "mgmt_dyn", "proto", "dhcp")
	x:set("network", "mgmt_dyn", "ifname", "br-mgmt")
	
	x:set("network", "mgmt_rescue", "interface")
	x:set("network", "mgmt_rescue", "proto", "static")
	x:set("network", "mgmt_rescue", "ipaddr", "192.168.1.1")
	x:set("network", "mgmt_rescue", "netmask", "255.255.255.0")
	x:set("network", "mgmt_rescue", "ifname", "br-mgmt")
end

local function clean()
	print("Clearing wireless config...")
	x:foreach("wireless", "wifi-iface", function(s) x:delete("wireless", s[".name"]) end)

	print("Clearing network config...")
	x:foreach("network", "interface", function(s)
		if s[".name"]:match("^mgmt$") or s[".name"]:match("^lan_") then
			x:delete("network", s[".name"])
		end
	end)
	x:foreach("network", "switch_vlan", function(s) x:delete("network", s[".name"]) end)
	x:foreach("network", "switch", function(s) x:delete("network", s[".name"]) end)
	x:delete("network", "wan")
	x:delete("network", "wan6")
	x:delete("network", "mgmt")
	x:delete("network", "lan")
end

local function exec_hooks()
	-- TODO
	print("Executing hooks ...")
	local hooks = {"a","b"}
	local _, p
	for _, p in ipairs(hooks) do
		local cmd = string.format("sh /etc/wibed/hooks/%s.sh")
		printf("-> Calling %s", cmd)
		os.execute(cmd)
	end
end

local function set_mgmt_wifi()
	print("Configuring management wifi devices")
	local channel5 = assert(x:get(ucic, "management", "channel5"))
	local ch = assert(x:get(ucic, "management", "channel2"))
	local i
	local _,ifaces = split_ifaces(x:get(ucic, "management", "ifaces"))	
	local wifi_num = 0

	for _,i in ipairs(ifaces) do
		local id = string.format("mgmt%d", wifi_num)
		local net = "bat_"..id

		local t = iw.type(i)
		if t then
			local is_5ghz = iw[t].hwmodelist(i).a

			if is_5ghz then ch=channel5 end
			if not ch then
				printf("-> No channel defined for %dGHz %s", is_5ghz and 5 or 2, i)
				return
			end
	
			local ht = ch:match("[-+]?$")
	
			printf("-> Using channel %s for %dGHz %s", ch, is_5ghz and 5 or 2, i)
			x:set("wireless", i, "channel", (ch:gsub("[-+]$", "")))
	
			if x:get("wireless", i, "ht_capab") then
				if ht == "+" or ht == "-" then
					x:set("wireless", i, "htmode", "HT40"..ht)
				else
					x:set("wireless", i, "htmode", "HT20")
				end
			end
	
			x:set("wireless", i, "disabled", 0)
			x:set("wireless", id, "wifi-iface")
			x:set("wireless", id, "device", i)
			x:set("wireless", id, "network", net)
			x:set("wireless", id, "mode", "adhoc")
			x:set("wireless", id, "ifname", id)

			set_batadv(id)
	
			wifi_num = wifi_num + 1
			else printf("-> Error, device %s not found as WiFi interface", i)
		end	
	end
end

function main()
	local r1, r2 = node_id()
	local batch = { }

	reset_wifi()
	clean()

	set_mgmt_net()
	set_mgmt_wifi()

	print("Committing config files...")
	x:save("network")
	x:save("batman-adv")
	x:save("wireless")
	x:commit("network")
	x:commit("batman-adv")
	x:commit("wireless")

	print("Configuring system...")
	set_hostname()
end

main()
