#!/bin/sh

list_neigh() {
	INT=${INT:-eth0}
	IPBRD=${IPBRD:-"ff02::2"}
	MYLOCALLINK="$(ip addr show dev $INT | grep -e "inet6.*scope link" | awk '{print $2}' | cut -d/ -f1)"
	NEIGH="$(ping6 ${IPBRD}%${INT} -n -c3 2>/dev/null | grep fe80 2>/dev/null | awk '{print $4}' | sed 's/\(.*\)./\1/' | grep -v "${MYLOCALLINK}"| sort -u)"
	echo "$NEIGH"
}


ssh_neigh() {

        if [ "$1" = "-d" ]
        then
                INT=$2
                shift 2
        else
                INT=${INT:-eth0}
        fi

        PARAM="$@"

        LNEIGH="$(INT=$INT list_neigh)"
        if [ $(echo -e "$LNEIGH" | wc -l) -gt 1 ]
        then
                cnt=1
                for i in ${LNEIGH}
                do
                        echo "$cnt.$i"
                        cnt=$(expr $cnt + 1)
                done
                nchar=$(echo -n $cnt| wc -c)
                read -n $nchar mychoice
                cnt=1
                for i in ${LNEIGH}
                do
                        if [ $mychoice -eq $cnt ]
                        then
                                CONNECT=$i
                        fi
                        cnt=$(expr $cnt + 1)
                done
                CONNECT=$CONNECT%$INT
                
        else
                CONNECT=$LNEIGH%$INT
        fi

        unset INT
        ssh $CONNECT ${PARAM}

}

ssh_neigh -d br-mgmt
