#!/bin/sh

rm -f /tmp/wibed-status.tmp 2>/dev/null
(wget "$(uci get wibed.general.api_url)" -q -O /tmp/wibed-status.tmp 1>/dev/null 2>&1) &
sleep 5
killall -9 wget 2>/dev/null

if [ -f "/tmp/wibed-status.tmp" ]; then 
	echo default-on > /sys/class/leds/tp-link\:blue\:qss/trigger
	echo "" > /tmp/wibed-status.watchdog
	RETURN=0
else
	echo timer > /sys/class/leds/tp-link\:blue\:qss/trigger
	echo "." >> /tmp/wibed-status.watchdog
	RETURN=1
fi

if [ $(cat /tmp/wibed-status.watchdog | wc -l) -gt 60 ]; then
	echo "Restoring defaults..." 
#	/sbin/firstboot -y 
	/sbin/reboot -f
fi

echo $RETURN
exit $RETURN
