#!/bin/sh -ex

DEVICE=${1:-"/dev/sda"}

[ -b $DEVICE ] || { echo "$DEVICE could not be found. Aborting."; exit 1; }

grep ^$DEVICE /proc/mounts && { echo "$DEVICE mounted. Aborting."; exit 2; }

dd if=/dev/zero of=$DEVICE bs=512 count=2

sync
sleep 1

sfdisk -L -q $DEVICE << EOF
,,L
EOF

sync
sleep 1

mkfs.ext4 -L wibed-overlay ${DEVICE}1 || { echo "Partitioning $DEVICE failed."; exit 3; }

/etc/init.d/fstab overlay_enable

exit 0

