#!/bin/sh

VERSION="$1"
HASH="$2"
MYHASH="$(md5sum /tmp/wibed.bin | awk '{print $1}')"
if [ "$HASH" == "$MYHASH" ] ; then
        echo "UPGRADING"
        sysupgrade -n /tmp/wibed.bin &
	sleep 1
	return 0
fi

echo "FAILED TO UPGRADE"
rm -f /tmp/wibed.bin
return 1
